"""
Django settings for eshop_project project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j*m(@j8q)n_p4z^x!^k1ek11r(1*wbg3kc)!_0t4)r-#wp6=9a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'eshop',
    'axes',  
    'django_extensions',  # Προσθήκη αυτής της γραμμής
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # Middleware for Django Axes
]

ROOT_URLCONF = 'eshop_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eshop_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Ρυθμίσεις για αρχεία media (εικόνες προϊόντων κλπ)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Security Settings
SECURE_SSL_REDIRECT = True  # Ανακατεύθυνση HTTP σε HTTPS
SESSION_COOKIE_SECURE = True  # Αποστολή cookies μόνο μέσω HTTPS
SECURE_BROWSER_XSS_FILTER = True  # Ενεργοποίηση του XSS φίλτρου των browsers
SECURE_CONTENT_TYPE_NOSNIFF = True  # Αποτροπή MIME-type sniffing
SECURE_HSTS_SECONDS = 31536000  # 1 χρόνος
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Εφαρμογή HSTS και σε subdomains
SECURE_HSTS_PRELOAD = True  # Συμπερίληψη στη HSTS preload list


# CSRF settings
CSRF_COOKIE_HTTPONLY = False  # Άφησέ το False για να μπορεί να προσπελαστεί από JavaScript
CSRF_COOKIE_SECURE = True  # Απαιτεί HTTPS για το CSRF cookie
CSRF_COOKIE_SAMESITE = 'Lax'  # Περιορίζει την αποστολή του cookie σε cross-site requests
CSRF_TRUSTED_ORIGINS = ['https://localhost:8000']  # Domains που επιτρέπονται για CSRF

# Για το περιβάλλον ανάπτυξης (θα απενεργοποιήσουμε προσωρινά το SSL redirect)
if DEBUG:
    SECURE_SSL_REDIRECT = False

# Προσωρινά για την ανάπτυξη
DEBUG = True

# URL για ανακατεύθυνση όταν απαιτείται σύνδεση
LOGIN_URL = 'login'  # Χρησιμοποιεί το name='login' από το urls.py

# Django-axes configuration
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Django-axes settings
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1  # in hours
AXES_LOCK_OUT_AT_FAILURE = True
AXES_RESET_ON_SUCCESS = True
AXES_ENABLED = True

# Use this instead of the deprecated settings:
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address", "user_agent"]]
