# Generated by Django 5.2.1 on 2025-05-19 13:04

import django.core.validators
import eshop.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_alter_shippingaddress_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='name',
            field=eshop.utils.fields.EncryptedCharField(max_length=900, verbose_name='Ονοματεπώνυμο'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=eshop.utils.fields.EncryptedCharField(help_text='Εισάγετε έγκυρο ελληνικό αριθμό τηλεφώνου (π.χ. 2101234567 ή 6981234567 ή +30 6981234567)', max_length=180, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Παρακαλώ εισάγετε έγκυρο ελληνικό αριθμό τηλεφώνου (σταθερό ή κινητό)', regex='^(?:\\+30|0030)?(?:\\s*)(?:(?:69\\d{8})|(?:2\\d{9}))$')], verbose_name='Τηλέφωνο'),
        ),
    ]
