# Generated by Django 5.2 on 2025-05-13 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_alter_shippingaddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(help_text='Εισάγετε έγκυρο ελληνικό αριθμό τηλεφώνου (π.χ. 2101234567 ή 6981234567 ή +30 6981234567)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Παρακαλώ εισάγετε έγκυρο ελληνικό αριθμό τηλεφώνου (σταθερό ή κινητό)', regex='^(?:\\+30|0030)?(?:\\s*)(?:(?:69\\d{8})|(?:2\\d{9}))$')], verbose_name='Τηλέφωνο'),
        ),
    ]
