# Generated by Django 5.2 on 2025-05-05 13:55

import eshop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_order_order_number_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=eshop.models.generate_order_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
