# Generated by Django 5.2 on 2025-05-13 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_random_order_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='email',
            field=models.EmailField(help_text='Απαιτείται για επικοινωνία σχετικά με την παραγγελία', max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(help_text='Εισάγετε έγκυρο ελληνικό αριθμό τηλεφώνου (π.χ. 2101234567 ή +30 2101234567)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Παρακαλώ εισάγετε έγκυρο ελληνικό αριθμό τηλεφώνου', regex='^(\\+30|0030)?\\s?[2-9]\\d{9}$')], verbose_name='Τηλέφωνο'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_zip_code', message='Ο ταχυδρομικός κώδικας πρέπει να αποτελείται από 5 ψηφία', regex='^\\d{5}$')], verbose_name='ΤΚ'),
        ),
    ]
